"""empty message

Revision ID: 494871dcb9cf
Revises: 841184963783
Create Date: 2018-11-19 19:10:59.453274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '494871dcb9cf'
down_revision = '841184963783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
