#FROM python:3.6.2-alpine
FROM python:3.6.5-slim
#RUN apk update && \
#    apk add --virtual build-deps gcc python-dev musl-dev && \
#    apk add postgresql-dev && \
#    apk add netcat-openbsd
RUN apt-get update && \
    apt-get -y install netcat && \
    apt-get clean


WORKDIR /usr/src/app

COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

COPY ./entrypoint.sh /usr/src/app/entrypoint.sh
RUN chmod 777 /usr/src/app/entrypoint.sh

COPY . /usr/src/app

CMD ["/usr/src/app/entrypoint.sh"]