#FROM python:3.6.5-alpine
FROM python:3.6.5-slim

WORKDIR /usr/src/app
COPY ./requirements.txt /usr/src/app/requirements.txt
#RUN apk update && \
#    apk add --no-cache --virtual build-deps gcc python-dev musl-dev && \
#    apk add --no-cache postgresql-dev && \
#    apk add --no-cache --virtual build-deps netcat-openbsd libffi-dev libffi
RUN apt-get update && \
    apt-get -y install netcat && \
    apt-get clean


#WORKDIR /usr/src/app

#COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip --no-cache-dir install -r requirements.txt
#RUN apk del build-deps
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh
RUN chmod 777 /usr/src/app/entrypoint.sh

COPY . /usr/src/app
CMD ["/usr/src/app/entrypoint.sh"]
